# Site settings
title: 'Monte Thakkar'
description: 'Young, independent and ambitious software engineer looking to work on challenging technical problems with a passion for developing mobile apps.'
url: 'https://monte9.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Monte Thakkar'
  email: mthakkar@mail.sfsu.edu
  twitter_username: MThakkar_
  facebook_username: MANTHANMAN
  github_username:  Monte9
  linkedin_username:  montethakkar

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
